apiVersion: 2019-12-01
location: southeastasia
name: aci-containergroup-ssftp
properties:
  containers:
  - name: sftp-server #sftp server
    properties:
      image: atmoz/sftp:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 2.5
      ports:
      - port: 22
      environmentVariables:
        - name: 'SFTP_USERS'
          value: 'sftpadmin:P@s$w0rd@123:::staging'
      volumeMounts:
      - mountPath: /home/sftpadmin/staging
        name: fs-staging

  - name: clamav-clamd  # ClamAv virus DB & Scan API daemon
    properties:
      image: mkodockx/docker-clamav
      resources:
        requests:
          cpu: 1
          memoryInGb: 2.5
      ports:
      - port: 3310

  - name: ssftp  # file scanner & quarantine
    properties:
      image: wxzd/ssftp:1.0
      resources:
        requests:
          cpu: 1
          memoryInGb: 2.5
      environmentVariables:
        - name: 'stagingPath'
          value: '/mnt/ssftp/staging'
        - name: 'cleanPath'
          value: '/mnt/ssftp/clean'
        - name: 'quarantinePath'
          value: '/mnt/ssftp/quarantine'
        - name: 'errorPath'
          value: '/mnt/ssftp/error'
        - name: 'logPath'
          value: '/mnt/ssftp/log'
        - name: 'virusFoundWebhookUrl'
          value: 'https://prod-00-ise-app-workflo-x3ftwztqrja52-internal.southeastasia.environments.microsoftazurelogicapps.net:443/workflows/05776bea6fe74ed58c7b55ea6f020e8a/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=OP_eiy0-2yC42dSNM8f-F5yl1cf2NN99lOMc2RMFeeM'
      volumeMounts:
      - mountPath: /mnt/ssftp/staging
        name: fs-staging
        readOnly: false
      - mountPath: /mnt/ssftp/clean
        name: fs-clean
        readOnly: false
      - mountPath: /mnt/ssftp/quarantine
        name: fs-quarantine
        readOnly: false
      - mountPath: /mnt/ssftp/error
        name: fs-error
        readOnly: false
      - mountPath: /mnt/ssftp/log
        name: fs-log
        readOnly: false
  volumes:
  - name: fs-staging
    azureFile:
      sharename: ssftp-staging
      storageAccountName: strgacisftpfileshare
      storageAccountKey: /QxRjgUHfNg304STRsR9WeMqP+ufvvERfAE5urZaHBqCo+XPPuhSXAdoXHQ9fuVSSKOVn6fDbTY/a4Gfc7tdBQ==
  - name: fs-clean
    azureFile:
      sharename: ssftp-clean
      storageAccountName: strgacisftpfileshare
      storageAccountKey: /QxRjgUHfNg304STRsR9WeMqP+ufvvERfAE5urZaHBqCo+XPPuhSXAdoXHQ9fuVSSKOVn6fDbTY/a4Gfc7tdBQ==
  - name: fs-quarantine
    azureFile:
      sharename: ssftp-quarantine
      storageAccountName: strgacisftpfileshare
      storageAccountKey: /QxRjgUHfNg304STRsR9WeMqP+ufvvERfAE5urZaHBqCo+XPPuhSXAdoXHQ9fuVSSKOVn6fDbTY/a4Gfc7tdBQ==
  - name: fs-error
    azureFile:
      sharename: ssftp-error
      storageAccountName: strgacisftpfileshare
      storageAccountKey: /QxRjgUHfNg304STRsR9WeMqP+ufvvERfAE5urZaHBqCo+XPPuhSXAdoXHQ9fuVSSKOVn6fDbTY/a4Gfc7tdBQ==
  - name: fs-log
    azureFile:
      sharename: ssftp-log
      storageAccountName: strgacisftpfileshare
      storageAccountKey: /QxRjgUHfNg304STRsR9WeMqP+ufvvERfAE5urZaHBqCo+XPPuhSXAdoXHQ9fuVSSKOVn6fDbTY/a4Gfc7tdBQ==
  
  ipAddress:
    type: Private
    ports:
    - protocol: tcp
      port: 22
  networkProfile:
    id: /subscriptions/ee611083-4581-4ba1-8116-a502d4539206/resourceGroups/rgGCCSHOL/providers/Microsoft.Network/networkProfiles/aci-network-profile-vnetInternetZone-Subnet-sSFTP
  restartPolicy: Always
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups