apiVersion: 2019-12-01
location: southeastasia
name: aci-containergroup-ssftp
properties:
  containers:
  - name: aci-tutorial-app
    properties:
      image: atmoz/sftp:latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 22
  - name: aci-tutorial-sidecar
    properties:
      image: mcr.microsoft.com/azuredocs/aci-tutorial-sidecar
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
    - protocol: tcp
      port: 8080
tags: {exampleTag: tutorial}
type: Microsoft.ContainerInstance/containerGroups