apiVersion: 2019-12-01
location: southeastasia
name: aci-ssftp
properties:
  containers:

  - name: clamav-clamd  # ClamAv virus DB & Scan API daemon
    properties:
      image: mkodockx/docker-clamav
      resources:
        requests:
          cpu: 1
          memoryInGb: 2.5
      ports:
      - port: 3310

  - name: ssftp  # file scanner & quarantine
    properties:
      image: wxzd/ssftp:1.0
      resources:
        requests:
          cpu: 1
          memoryInGb: 2.5
      ports:
        - port: 22
      
      volumeMounts: # mountPath by convention, don't change path
      - mountPath: /mnt/ssftp/staging
        name: fs-staging
        readOnly: false
      - mountPath: /mnt/ssftp/clean
        name: fs-clean
        readOnly: false
      - mountPath: /mnt/ssftp/quarantine
        name: fs-quarantine
        readOnly: false
      - mountPath: /mnt/ssftp/error
        name: fs-error
        readOnly: false
      - mountPath: /mnt/ssftp/log         # optional, if exist to match LogSink.Path in ssftp.yaml
        name: fs-log
        readOnly: false
      - mountPath: /mnt/ssftp/system
        name: fs-system
        readOnly: false
  volumes:
  - name: fs-staging
    azureFile:
      sharename: ssftp-staging
      storageAccountName: <storage name>  # all storage name and keys "commonly" the same due to same AzStorage used
      storageAccountKey: <storage key>
  - name: fs-clean
    azureFile:
      sharename: ssftp-clean
      storageAccountName: <storage name>
      storageAccountKey: <storage key>
  - name: fs-quarantine
    azureFile:
      sharename: ssftp-quarantine
      storageAccountName: <storage name>
      storageAccountKey: <storage key>
  - name: fs-error
    azureFile:
      sharename: ssftp-error
      storageAccountName: <storage name>
      storageAccountKey: <storage key>
  - name: fs-log
    azureFile:
      sharename: ssftp-log
      storageAccountName: <storage name>
      storageAccountKey: <storage key>
  - name: fs-system
    azureFile:
      sharename: ssftp-system
      storageAccountName: <storage name>
      storageAccountKey: <storage key>
  
  ipAddress:
    type: Private
    ports:
    - protocol: tcp
      port: 22
  networkProfile:
    id: < network profile >
  restartPolicy: Always
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups