apiVersion: 2019-12-01
location: southeastasia
name: aci-containergroup-ssftp
properties:
  containers:
  - name: sftp-server
    properties:
      image: atmoz/sftp:latest
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 22
  - name: ssftp
    properties:
      image: wxzd/ssftp:1.0
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
  - name: clamd
    properties:
      image: mkodockx/docker-clamav
      resources:
        requests:
          cpu: 2
          memoryInGb: 4
      ports:
      - port: 3310
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
    - protocol: tcp
      port: 8080
tags: {exampleTag: tutorial}
type: Microsoft.ContainerInstance/containerGroups