apiVersion: 2019-12-01
location: southeastasia
name: aci-ssftp
properties:
  containers:

  - name: clamav  # ClamAV virus DB & Clamd Scan API daemon
    properties:
      image: mkodockx/docker-clamav:alpine
      environmentVariables:
      - name: CLAMD_CONF_FILE
        value: /mnt/ssftp/system/clamd.conf
      resources:
        requests:
          cpu: 2
          memoryInGb: 8
      ports:
      - port: 3310
      volumeMounts:                                 #Note: mountPath by convention, don't change path
       - mountPath: /mnt/ssftp/system
         name: fs-system
         readOnly: false
       - mountPath: /mnt/ssftp/staging
         name: fs-staging
         readOnly: false

  - name: ssftp  # file scanner & quarantine
    properties:
      image: wxzd/ssftp:1.0
      resources:
        requests:
          cpu: 2
          memoryInGb: 8
      ports:
        - port: 22
      volumeMounts:                                 #Note: mountPath by convention, don't change path
      - mountPath: /mnt/ssftp/staging
        name: fs-staging
        readOnly: false
      - mountPath: /mnt/ssftp/clean
        name: fs-clean
        readOnly: false
      - mountPath: /mnt/ssftp/quarantine
        name: fs-quarantine
        readOnly: false
      - mountPath: /mnt/ssftp/error
        name: fs-error
        readOnly: false
      - mountPath: /mnt/ssftp/log                   #input - optional, if exist to match LogSink.Path in ssftp.yaml
        name: fs-log
        readOnly: false
      - mountPath: /mnt/ssftp/system
        name: fs-system
        readOnly: false
  volumes:
  - name: fs-staging
    azureFile:
      sharename: ssftp-staging
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  - name: fs-clean
    azureFile:
      sharename: ssftp-clean
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  - name: fs-quarantine
    azureFile:
      sharename: ssftp-quarantine
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  - name: fs-error
    azureFile:
      sharename: ssftp-error
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  - name: fs-log
    azureFile:
      sharename: ssftp-log
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  - name: fs-system
    azureFile:
      sharename: ssftp-system
      storageAccountName: <storage accountn name>   #input
      storageAccountKey: <storage account key>      #input
  
  ipAddress:
    type: Private
    ports:
    - protocol: tcp
      port: 22
  networkProfile:
    id: <network profile resource ID>               #input
  restartPolicy: Always
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups