name: aci-ssftp-intranetzone
apiVersion: '2019-12-01'
location: southeastasia
properties:
  containers:
  - name: clamav
    properties:
      image: mkodockx/docker-clamav:alpine
      resources:
        requests:
          cpu: 1
          memoryInGb: 4
      ports:
      - port: 3310
      volumeMounts:                       # mountPath by convention, don't change path
       - mountPath: /mnt/ssftp/system
         name: fs-system
       - mountPath: /mnt/ssftp/staging
         name: fs-staging
  - name: ssftp
    properties:
      image: wxzd/ssftp:1.2.0
      resources:
        requests:
          cpu: 1
          memoryInGb: 4
      ports:
        - port: 2002
      volumeMounts:                         # mountPath by convention, don't change path
      - mountPath: /mnt/ssftp/staging       
        name: fs-staging
      - mountPath: /mnt/ssftp/uploadarchive 
        name: fs-uploadarchive
      - mountPath: /mnt/ssftp/clean         
        name: fs-clean
      - mountPath: /mnt/ssftp/quarantine
        name: fs-quarantine
      - mountPath: /mnt/ssftp/log           # optional but recommended. If exist to match LogSink.Path in ssftp.yaml
        name: fs-log
      - mountPath: /mnt/ssftp/system
        name: fs-system
  volumes:
  - name: fs-staging
    azureFile:
      sharename: ssftp-staging
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  - name: fs-uploadarchive
    azureFile:
      sharename: ssftp-uploadarchive
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  - name: fs-clean
    azureFile:
      sharename: ssftp-clean
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  - name: fs-quarantine
    azureFile:
      sharename: ssftp-quarantine
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  - name: fs-log
    azureFile:
      sharename: ssftp-log
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  - name: fs-system
    azureFile:
      sharename: ssftp-system
      storageAccountName: <storage accountn name> #input
      storageAccountKey: <storage account key>    #input
  ipAddress:
    type: Private
    ports:
    - protocol: tcp
      port: 2002                                  #input: port must match container port above & "sftpPort" in ssftp.yaml
  networkProfile:
    id: <network profile resource ID>             #input
  restartPolicy: Always
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups