name: sSFTP-Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Go build
      run: go build -v ./src
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wxzd/ssftp:1.2.3
