name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Go build
      run: |
       cd src
       cd ssftp
       ls
       go build
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker Build
      run: |
        docker build  --no-cache -f ./src/ssftp/Dockerfile -t wxzd/ssftp:1.3.2 .
