name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Get version number
      id: versionnumber
      run: echo "VERSION_NUMBER=${{fromJson(steps.readfile.outputs.content).main}}"  >> $GITHUB_ENV
      
    - name: Print version number
      run: echo ${{ env.VERSION_NUMBER }}

    - name: Set up Go
      uses: actions/setup-go@v2
      if: ${{ env.VERSION_NUMBER }} != ""
      with:
        go-version: 1.15
        
    - name: Go build
      if: ${{ env.VERSION_NUMBER }} != ""
      run: |
       cd src
       cd ssftp
       ls
       go build
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker Build
      run: |
        docker build  --no-cache -f ./src/ssftp/Dockerfile -t wxzd/ssftp:${{ env.VERSION_NUMBER }} .
    
    - name: Docker Push
      run: |
        docker push  wxzd/ssftp:${{ env.VERSION_NUMBER }}
        
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Replace version in ACI Yaml
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "{{VERSION_NUMBER}}"
        replace: ${{ env.VERSION_NUMBER }}
        include: "deploy/aci/internet/deploy-aci-internetzone.yaml"
        
    - name: Remove existing ACI Internet Zone
      run: az container delete -g rgGCCSHOL -n aci-ssftp-internetzone -y
        
    - name: Deploy sSFTP to ACI Internet Zone
      run:  |
        cd deploy/aci/internet
        az container create -g rgGCCSHOL --file deploy/aci/internet/deploy-aci-internetzone.yaml
 
  
