name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Set version number Env Var
      run: |
        echo "SEMANTIC_VERSION=${{ fromJson(steps.readfile.outputs.content).main}} "  >> $GITHUB_ENV
        echo ${{ env.SEMANTIC_VERSION }}
    
    
