name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: List files
      run: |
        ls   
    
    - name: Read package.json
      uses: juliangruber/read-file-action@v1
      with:
       path: .github/workflows/version.json
    
    
