name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      uses: juliangruber/read-file-action@v1
      with:
        path: ./version.json
        
    - name: Get version number
      run: echo ${{ fromJson(steps.package.outputs.content) }}
