name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
  
    env:
      VERSION: 1.2.2
            
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Get version number
      run: |
        echo "VERSION = ${{ fromJson(steps.readfile.outputs.content).main }}"
        echo $VERSION
    
    
