name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Get version number
      run: |
        echo "::set-env version=${{ fromJson(steps.package.outputs.content).main }}"
        echo version
    
    
