name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Get version number
      id: versionnumber
      run: echo "VERSION_NUMBER=${{fromJson(steps.readfile.outputs.content).main}}"  >> $GITHUB_ENV
      
    - name: Print version number
      run: echo ${{ env.VERSION_NUMBER }}
    
    
