name: sSFTP-Main

on:
  push:
    branches: [ main ]
    paths: 
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths: 
      - "/src/*"

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Read version.json
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
       path: ./version.json
       
    - name: Get version number
      id: versionnumber
      run: echo "VERSION_NUMBER=${{fromJson(steps.readfile.outputs.content).main}}"  >> $GITHUB_ENV
      
    - name: Print version number
      run: echo ${{ env.VERSION_NUMBER }}

    - name: Set up Go
      uses: actions/setup-go@v2
      if: ${{ env.VERSION_NUMBER }} != ""
      with:
        go-version: 1.15
        
    - name: Go build
      if: ${{ env.VERSION_NUMBER }} != ""
      run: |
       cd src
       cd ssftp
       ls
       go build
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Docker Build
      run: |
        docker build  --no-cache -f ./src/ssftp/Dockerfile -t wxzd/ssftp:${{ env.VERSION_NUMBER }} .
    
    - name: Docker Push
      run: |
        docker push  wxzd/ssftp:${{ env.VERSION_NUMBER }}
    
    
